version: '3.4'

services:
  contact.api:
    image: ${DOCKER_REGISTRY-}contactapi
    build:
      context: .
      dockerfile: Contact.API/Dockerfile

  contactdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4